### ISSUE TITLE
KeyError at /clientcreds/get_consent/

### ISSUE THREAD

**Issue by paulyyi** [jasonjoh/python_clientcred#4]
Hello,
Thanks for this project, I hope to get it working.

After I accept permissions as administrator, I receive this error.  

KeyError at /clientcreds/get_consent/
'access_token'
Request Method:	POST
Request URL:	http://127.0.0.1:8000/clientcreds/get_consent/
Django Version:	1.7.1
Exception Type:	KeyError
Exception Value:	
'access_token'
Exception Location:	C:\Users\robert\Downloads\python_clientcred-master\clientcreds\views.py in consent, line 29
Python Executable:	C:\Python34\python.exe
Python Version:	3.4.2
Python Path:	
['C:\\Users\\robert\\Downloads\\python_clientcred-master',
 'C:\\WINDOWS\\SYSTEM32\\python34.zip',
 'C:\\Python34\\DLLs',
 'C:\\Python34\\lib',
 'C:\\Python34',
 'C:\\Python34\\lib\\site-packages']
Server time:	Wed, 7 Oct 2015 13:15:17 -0700

what could be causing this? Any help is appreciated

**Comment by paulyyi** [comment]
Some more info
access_token	
{'correlation_id': '342b2466-5da2-472d-b78d-7614a649257c',
 'error': 'invalid_client',
 'error_codes': [70002, 50012],
 'error_description': 'AADSTS70002: Error validating credentials. '
                      'AADSTS50012: Client assertion contains an invalid '
                      'signature.\r\n'
                      'Trace ID: 893922e8-3981-4f85-a013-71f1afec793f\r\n'
                      'Correlation ID: '
                      '342b2466-5da2-472d-b78d-7614a649257c\r\n'
                      'Timestamp: 2015-10-07 21:53:08Z',
 'timestamp': '2015-10-07 21:53:08Z',
 'trace_id': '893922e8-3981-4f85-a013-71f1afec793f'}

**Comment by jasonjoh** [comment]
I see you closed this, did you figure it out?
